### ISSUE TITLE
sym_rss_image_fast test failing.

### ISSUE THREAD

**Issue by iras** [evankroske/rotation-symmetry-detector#1]
Hi @evankroske.

The sym_rss_image_fast test seems to be failing.

Also, I do imwrite(rss_image, 'path') at the end but does not seem to work with the fractal image. Any thoughts would be appreciated.

Thanks.

**Comment by evankroske** [comment]
Sorry, I'm not maintaining this project anymore. If you'd like to fix this problem, I'd be happy to review your PR.
